schedules:
  - cron: 0 4 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - master

resources:
  pipelines:
  - pipeline: build
    source: YAML Pipelines Testing - Build
    trigger:
      tags:
        - Integrate
  repositories:
  - repository: master
    type: github
    endpoint: dave-yotta
    name: dave-yotta/yaml-master-repo
    trigger:
      branches:
        include:
        - master
    pr:
      branches:
        include:
        - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- download: build
  target: .

- template: hello-args.yaml
  parameters:
    name: integrate-san

- script: |
    echo i shall be deployed! > deployment-file
    cat build/build-file >> deployment-file
    echo "1.0.0" >> deployment-file
  displayName: 'make a deployable file lol'
  failOnStderr: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: deployment-file
    artifact: deploy
    publishLocation: pipeline