stages:
- stage: labs
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: labs
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: staging
  dependsOn: labs
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: prod
  dependsOn: staging
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world