trigger: none

stages:
- stage: labs
  condition: eq(2,1)
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-labs
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: staging
  dependsOn: labs
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: prod
  dependsOn: staging
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world