trigger: none
schedules:
  - cron: 0 4 * * *
    displayName: Nightly
    always: true

stages:
- stage: labs
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-labs
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: staging
  dependsOn: labs
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: prod
  dependsOn: staging
  jobs:
  - deployment: DeployWeb
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world