trigger: none

resources:
  pipelines:
  - pipeline: build
    source: YAML Pipelines Testing - Build
    trigger: none
    tags:
      - Nightly
  - pipeline: integrate
    source: YAML Pipelines Testing - Integrate
    trigger:
      enabled: true
      tags:
        - Nightly

stages:
- stage: labs
  jobs:
  - deployment: deploy_stuff
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-labs
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: staging
  dependsOn: labs
  jobs:
  - deployment: deploy_stuff
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- stage: prod
  dependsOn: staging
  jobs:
  - deployment: deploy_stuff
    displayName: deploy file!
    pool:
      vmImage: 'Ubuntu-latest'
    environment: yaml-test-prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world