schedules:
  - cron: 0 4 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - master

variables:
- template: api-vars.yaml

resources:
  pipelines:
  - pipeline: build
    source: YAML Pipelines Testing - Build
    trigger:
      tags:
        - Integrate
  repositories:
  - repository: master
    type: github
    endpoint: dave-yotta
    name: dave-yotta/yaml-master-repo
    trigger:
      branches:
        include:
        - master
    pr:
      branches:
        include:
        - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: specific
    project: $(System.TeamProjectId)
    definition: $(Resources.Pipeline.Build.PipelineId)
    specificBuildWithTriggering: true
    buildVersionToDownload: latestFromBranch
    branchName: refs/heads/master
    targetPath: .

- template: hello-args.yaml
  parameters:
    name: integrate-san

- script: |
    env
    echo i shall be deployed! > deployment-file
    cat build/build-file >> deployment-file
    echo "1.0.0" >> deployment-file
  displayName: 'make a deployable file lol'
  failOnStderr: true

- script: |
    curl $(api.headers) -X PUT $(api.uri)/builds/build/$(Resources.Pipeline.Build.RunId)/tags/Integrate
    curl $(api.headers) -X PUT $(api.build.uri)/tags/Integrate
  displayName: tag builds with Nightly

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: deployment-file
    artifact: deploy
    publishLocation: pipeline