schedules:
  - cron: 0 4 * * *
    displayName: Nightly
    always: true

resources:
  repositories:
  # a build repository (we can have many)
  - repository: slave
    type: github
    endpoint: dave-yotta
    name: dave-yotta/yaml-slave-repo
    trigger:
      branches:
        include:
        - master
    pr:
      branches:
        include:
        - master
  # our infrastructure repository
  - repository: master
    type: github
    endpoint: dave-yotta
    name: dave-yotta/yaml-master-repo
    trigger:
      branches:
        include:
        - master
    pr:
      branches:
        include:
        - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: hello-args.yaml
  parameters:
    name: integrate-san

- script: |
    echo i shall be deployed! > deployment-file
    echo "1.0.0" >> deployment-file
  displayName: 'make a deployable file lol'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: deployment-file
    artifact: deploy
    publishLocation: pipeline
